pipeline {
    agent any
    tools {
        maven 'Maven'
    }

    stages {
        stage("build") {
            steps {
                echo 'building the application...'
                sh 'mvn -B clean package'
                echo 'building succeeded!'
            }
        }
        stage("test") {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
         stage("deploy") {
                    steps {
                        sh 'chmod +x ./jenkins/deliver.sh'  // Ensure execution permission
                        sh './jenkins/deliver.sh'
                    }
                }
            }
        }
